# Generated by Django 5.0 on 2025-06-02 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_application_auditor_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='auditor_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='blog.auditorcompany'),
        ),
    ]
