# Generated by Django 5.0 on 2026-04-15 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_company_last_edited_at_company_responsible_editor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='responsible_editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='edited_companies', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за редактирование'),
            preserve_default=False,
        ),
    ]
